
package Modulo_3.Vista3;
import java.awt.Color;

import javax.swing.JFrame;

/**
 *
 * @author Usuario
 */
public class InterfazLogin extends javax.swing.JFrame {

    int Xmouse, Ymouse;
    public InterfazLogin() {
        initComponents();
        setSize(1196,700);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */                         
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        JpanelFondo = new javax.swing.JPanel();
        Barra = new javax.swing.JPanel();
        BotonExit = new javax.swing.JPanel();
        LabelDeSalida = new javax.swing.JLabel();
        PanelImagen = new javax.swing.JPanel();
        ImagenDecorativa = new javax.swing.JLabel();
        PanelLogin = new javax.swing.JPanel();
        MensajeLogin = new javax.swing.JLabel();
        Fondoblack1 = new javax.swing.JPanel();
        TextFieldCedula = new javax.swing.JTextField();
        Fondoblack2 = new javax.swing.JPanel();
        TomaDeContraseña = new javax.swing.JPasswordField();
        LogoLogin = new javax.swing.JLabel();
        MensajeLogin1 = new javax.swing.JLabel();
        MensajeLogin2 = new javax.swing.JLabel();
        jPanelRegistro = new javax.swing.JPanel();
        LabelRegistro = new javax.swing.JLabel();
        jPanellogin = new javax.swing.JPanel();
        LabelInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        JpanelFondo.setBackground(new java.awt.Color(255, 255, 255));
        JpanelFondo.setLayout(null);

        Barra.setBackground(new java.awt.Color(255, 255, 255));
        Barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraMouseDragged(evt);
            }
        });
        Barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraMousePressed(evt);
            }
        });
        Barra.setLayout(null);

        BotonExit.setBackground(new java.awt.Color(255, 255, 255));
        BotonExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonExitMouseExited(evt);
            }
        });

        LabelDeSalida.setBackground(new java.awt.Color(0, 0, 0));
        LabelDeSalida.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LabelDeSalida.setForeground(new java.awt.Color(0, 0, 0));
        LabelDeSalida.setText("X");

        javax.swing.GroupLayout BotonExitLayout = new javax.swing.GroupLayout(BotonExit);
        BotonExit.setLayout(BotonExitLayout);
        BotonExitLayout.setHorizontalGroup(
            BotonExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonExitLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(LabelDeSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        BotonExitLayout.setVerticalGroup(
            BotonExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelDeSalida, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        Barra.add(BotonExit);
        BotonExit.setBounds(1130, 0, 70, 40);

        JpanelFondo.add(Barra);
        Barra.setBounds(0, 0, 1210, 40);

        PanelImagen.setBackground(new java.awt.Color(255, 255, 255));
        PanelImagen.setLayout(null);
        
        ImagenDecorativa.setBackground(new java.awt.Color(0, 0, 0));
        ImagenDecorativa.setForeground(new java.awt.Color(0, 0, 0));
        ImagenDecorativa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Principal.jpg"))); // NOI18N
        ImagenDecorativa.setText("jLabel1");
        PanelImagen.add(ImagenDecorativa);
        ImagenDecorativa.setBounds(0, 0, 700, 700);

        JpanelFondo.add(PanelImagen);
        PanelImagen.setBounds(0, 0, 700, 700);

        PanelLogin.setBackground(new java.awt.Color(32, 117, 135));
        PanelLogin.setLayout(null); // Aseguramos layout libre para que respete los bounds y agregados

        MensajeLogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        MensajeLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MensajeLogin.setText("Bienvenidos al Sistema de Transporte de la UCV");
        PanelLogin.add(MensajeLogin);
        MensajeLogin.setBounds(55, 330, 380, 30);

        Fondoblack1.setBackground(new java.awt.Color(0, 0, 0));
        Fondoblack1.setLayout(null);

        TextFieldCedula.setBackground(new java.awt.Color(255, 255, 255));
        TextFieldCedula.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextFieldCedula.setForeground(new java.awt.Color(51, 51, 51));
        TextFieldCedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldCedula.setText("Ingrese Cedula");
        TextFieldCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextFieldCedulaMousePressed(evt);
            }
        });
        Fondoblack1.add(TextFieldCedula);
        TextFieldCedula.setBounds(20, 0, 360, 40);

        PanelLogin.add(Fondoblack1);
        Fondoblack1.setBounds(55, 450, 400, 40);

        Fondoblack2.setBackground(new java.awt.Color(0, 0, 0));
        Fondoblack2.setLayout(null);

        TomaDeContraseña.setBackground(new java.awt.Color(255, 255, 255));
        TomaDeContraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TomaDeContraseña.setText("********");
        TomaDeContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TomaDeContraseñaMousePressed(evt);
            }
        });
        Fondoblack2.add(TomaDeContraseña);
        TomaDeContraseña.setBounds(20, 0, 360, 40);

        PanelLogin.add(Fondoblack2);
        Fondoblack2.setBounds(55, 510, 400, 40);

        LogoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/IMG-20260925-WA0003.jpg"))); // NOI18N
        PanelLogin.add(LogoLogin);
        LogoLogin.setBounds(93, 145, 302, 155);

        MensajeLogin1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        MensajeLogin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MensajeLogin1.setText("Porfavor ingrese sus datos para ");
        PanelLogin.add(MensajeLogin1);
        MensajeLogin1.setBounds(55, 370, 380, 20);

        MensajeLogin2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        MensajeLogin2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MensajeLogin2.setText("acceder al sistema");
        PanelLogin.add(MensajeLogin2);
        MensajeLogin2.setBounds(55, 395, 380, 20);

        jPanelRegistro.setBackground(new java.awt.Color(45, 191, 166));
        jPanelRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelRegistroMouseExited(evt);
            }
        });
        jPanelRegistro.setLayout(null);

        LabelRegistro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabelRegistro.setForeground(new java.awt.Color(0, 0, 0));
        LabelRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelRegistro.setText("Registrarse");
        jPanelRegistro.add(LabelRegistro);
        LabelRegistro.setBounds(0, 0, 280, 35);

        PanelLogin.add(jPanelRegistro);
        jPanelRegistro.setBounds(107, 570, 280, 35);

        jPanellogin.setBackground(new java.awt.Color(234, 197, 48));
        jPanellogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanellogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelloginMouseExited(evt);
            }
        });
        jPanellogin.setLayout(null);

        LabelInicio.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabelInicio.setForeground(new java.awt.Color(0, 0, 0));
        LabelInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelInicio.setText("Iniciar Secion");
        jPanellogin.add(LabelInicio);
        LabelInicio.setBounds(0, 0, 280, 35);

        PanelLogin.add(jPanellogin);
        jPanellogin.setBounds(107, 615, 280, 35);

        JpanelFondo.add(PanelLogin);
        PanelLogin.setBounds(700, 0, 500, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1196, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>/editor-fold>                        

    private void BarraMousePressed(java.awt.event.MouseEvent evt) {                                   
        Xmouse=evt.getX();
        Ymouse=evt.getY();
    }                                  

    private void BarraMouseDragged(java.awt.event.MouseEvent evt) {                                   
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-Xmouse, y-Ymouse);
    }                                  

    private void BotonExitMouseClicked(java.awt.event.MouseEvent evt) {                                       
        System.exit(0);
    }                                      

    private void BotonExitMouseEntered(java.awt.event.MouseEvent evt) {                                       
       BotonExit.setBackground(Color.red);
       LabelDeSalida.setForeground(Color.WHITE);
    }                                      

    private void BotonExitMouseExited(java.awt.event.MouseEvent evt) {                                      
       BotonExit.setBackground(Color.white);
       LabelDeSalida.setForeground(Color.BLACK);
    }                                     

    private void jPanelRegistroMouseEntered(java.awt.event.MouseEvent evt) {                                            
        jPanelRegistro.setBackground(new Color(57,242,210));
        LabelRegistro.setForeground(Color.white);
    }                                           

    private void jPanelRegistroMouseExited(java.awt.event.MouseEvent evt) {                                           
       jPanelRegistro.setBackground(new Color(45,191,166));
        LabelRegistro.setForeground(Color.black);
    }                                          

    private void jPanelloginMouseEntered(java.awt.event.MouseEvent evt) {                                         
        jPanellogin.setBackground(new Color(241,190,65));
        LabelInicio.setForeground(Color.white);
    }                                        

    private void jPanelloginMouseExited(java.awt.event.MouseEvent evt) {                                        
       jPanellogin.setBackground(new Color(234,197,48));
        LabelInicio.setForeground(Color.black);
    }                                       

    private void TextFieldCedulaMousePressed(java.awt.event.MouseEvent evt) {                                             
        TextFieldCedula.setText("");
        TomaDeContraseña.setText("********");
    }                                            

    private void TomaDeContraseñaMousePressed(java.awt.event.MouseEvent evt) {                                              
        TextFieldCedula.setText("Ingrese Cedula");
        TomaDeContraseña.setText("");
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel Barra;
    private javax.swing.JPanel BotonExit;
    private javax.swing.JPanel Fondoblack1;
    private javax.swing.JPanel Fondoblack2;
    private javax.swing.JLabel ImagenDecorativa;
    private javax.swing.JPanel JpanelFondo;
    private javax.swing.JLabel LabelDeSalida;
    private javax.swing.JLabel LabelInicio;
    private javax.swing.JLabel LabelRegistro;
    private javax.swing.JLabel LogoLogin;
    private javax.swing.JLabel MensajeLogin;
    private javax.swing.JLabel MensajeLogin1;
    private javax.swing.JLabel MensajeLogin2;
    private javax.swing.JPanel PanelImagen;
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JTextField TextFieldCedula;
    private javax.swing.JPasswordField TomaDeContraseña;
    private javax.swing.JPanel jPanelRegistro;
    private javax.swing.JPanel jPanellogin;
    // End of variables declaration                   
}
