/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modulo_6.Vista6;
import Modulo_7.Vista7.Interfazitinerario1;
import java.awt.Color;

/**
 *
 * @author Usuario
 */
public class InterfazDeFlota2 extends javax.swing.JFrame {
    private javax.swing.JTable tablaPrincipal;//añadido
    int Xmouse, Ymouse;
    private InterfazDeFlota1 interfazFlota1;
    public InterfazDeFlota2() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }//añadido
    public InterfazDeFlota2(InterfazDeFlota1 ventana1) {
    initComponents();
    this.interfazFlota1 = ventana1;
    // Opcional para que al cerrar la ventana 2 no se cierre todo el programa:
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
}
    //añadido
    public InterfazDeFlota2(javax.swing.JTable Tabla) {
        initComponents();
        this.tablaPrincipal = Tabla;
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtConductor = new javax.swing.JTextField();
        txtFlota = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtUnidad = new javax.swing.JTextField();
        txtCapacidad = new javax.swing.JTextField();
        GuardarUnidad = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BarraMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        FotoPerfil = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        MenuExpandido = new javax.swing.JPanel();
        Seccion1 = new javax.swing.JPanel();
        LabelSeccion1 = new javax.swing.JLabel();
        Seccion2 = new javax.swing.JPanel();
        LabelSeccion2 = new javax.swing.JLabel();
        Seccion3 = new javax.swing.JPanel();
        LabelSeccion3 = new javax.swing.JLabel();
        Seccion4 = new javax.swing.JPanel();
        LabelSeccion4 = new javax.swing.JLabel();
        Barra = new javax.swing.JPanel();
        BotonExit = new javax.swing.JPanel();
        LabelDeSalida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nueva Unidad");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        txtConductor.setBackground(new java.awt.Color(255, 255, 255));
        txtConductor.setForeground(new java.awt.Color(0, 0, 0));
        txtConductor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtConductor.setText("Ingrese Conductor");
        txtConductor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtConductorMousePressed(evt);
            }
        });
        txtConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConductorActionPerformed(evt);
            }
        });
        jPanel2.add(txtConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 300, 40));

        txtFlota.setBackground(new java.awt.Color(255, 255, 255));
        txtFlota.setForeground(new java.awt.Color(0, 0, 0));
        txtFlota.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFlota.setText("Ingrese Flota");
        txtFlota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFlotaMousePressed(evt);
            }
        });
        txtFlota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFlotaActionPerformed(evt);
            }
        });
        jPanel2.add(txtFlota, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 300, 40));

        txtPlaca.setBackground(new java.awt.Color(255, 255, 255));
        txtPlaca.setForeground(new java.awt.Color(0, 0, 0));
        txtPlaca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPlaca.setText("Ingrese Placa");
        txtPlaca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPlacaMousePressed(evt);
            }
        });
        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });
        jPanel2.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 300, 40));

        txtEstado.setBackground(new java.awt.Color(255, 255, 255));
        txtEstado.setForeground(new java.awt.Color(0, 0, 0));
        txtEstado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEstado.setText("Ingrese Estado");
        txtEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEstadoMousePressed(evt);
            }
        });
        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });
        jPanel2.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 300, 40));

        txtModelo.setBackground(new java.awt.Color(255, 255, 255));
        txtModelo.setForeground(new java.awt.Color(0, 0, 0));
        txtModelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtModelo.setText("Ingrese Modelo");
        txtModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtModeloMousePressed(evt);
            }
        });
        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });
        jPanel2.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 300, 40));

        txtUnidad.setBackground(new java.awt.Color(255, 255, 255));
        txtUnidad.setForeground(new java.awt.Color(0, 0, 0));
        txtUnidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUnidad.setText("Ingrese Unidad");
        txtUnidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUnidadMousePressed(evt);
            }
        });
        txtUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidadActionPerformed(evt);
            }
        });
        jPanel2.add(txtUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 300, 40));

        txtCapacidad.setBackground(new java.awt.Color(255, 255, 255));
        txtCapacidad.setForeground(new java.awt.Color(0, 0, 0));
        txtCapacidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCapacidad.setText("Ingrese número de la Unidad");
        txtCapacidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCapacidadMousePressed(evt);
            }
        });
        txtCapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapacidadActionPerformed(evt);
            }
        });
        jPanel2.add(txtCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 300, 40));

        GuardarUnidad.setBackground(new java.awt.Color(244, 208, 63));
        GuardarUnidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarUnidadMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Guardar");

        javax.swing.GroupLayout GuardarUnidadLayout = new javax.swing.GroupLayout(GuardarUnidad);
        GuardarUnidad.setLayout(GuardarUnidadLayout);
        GuardarUnidadLayout.setHorizontalGroup(
            GuardarUnidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuardarUnidadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );
        GuardarUnidadLayout.setVerticalGroup(
            GuardarUnidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GuardarUnidadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(GuardarUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 140, 40));

        Fondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 450, 570));

        jPanel3.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modulo_6/Image/Fondo 1.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 560));

        Fondo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 750, 560));

        BarraMenu.setBackground(new java.awt.Color(32, 135, 117));

        jPanel1.setBackground(new java.awt.Color(32, 135, 117));

        FotoPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FotoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modulo_6/Image/Perfil.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FotoPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FotoPerfil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Universidad Central de Venezuela");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sistema de Transporte");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modulo_6/Image/Menu.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BarraMenuLayout = new javax.swing.GroupLayout(BarraMenu);
        BarraMenu.setLayout(BarraMenuLayout);
        BarraMenuLayout.setHorizontalGroup(
            BarraMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraMenuLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(BarraMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraMenuLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraMenuLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(277, 277, 277)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BarraMenuLayout.setVerticalGroup(
            BarraMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BarraMenuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(27, 27, 27))
        );

        Fondo.add(BarraMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1200, 120));

        MenuExpandido.setBackground(new java.awt.Color(19, 79, 69));
        MenuExpandido.setLayout(new javax.swing.BoxLayout(MenuExpandido, javax.swing.BoxLayout.Y_AXIS));

        Seccion1.setBackground(new java.awt.Color(19, 79, 69));
        Seccion1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Seccion1.setMaximumSize(new java.awt.Dimension(32767, 30));
        Seccion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Seccion1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Seccion1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Seccion1MouseExited(evt);
            }
        });

        LabelSeccion1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabelSeccion1.setForeground(new java.awt.Color(255, 255, 255));
        LabelSeccion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSeccion1.setText("Ver Itinearios");

        javax.swing.GroupLayout Seccion1Layout = new javax.swing.GroupLayout(Seccion1);
        Seccion1.setLayout(Seccion1Layout);
        Seccion1Layout.setHorizontalGroup(
            Seccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Seccion1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelSeccion1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );
        Seccion1Layout.setVerticalGroup(
            Seccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Seccion1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelSeccion1)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        MenuExpandido.add(Seccion1);

        Seccion2.setBackground(new java.awt.Color(19, 79, 69));
        Seccion2.setForeground(new java.awt.Color(19, 79, 69));
        Seccion2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Seccion2.setMaximumSize(new java.awt.Dimension(32767, 30));
        Seccion2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Seccion2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Seccion2MouseExited(evt);
            }
        });

        LabelSeccion2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabelSeccion2.setForeground(new java.awt.Color(255, 255, 255));
        LabelSeccion2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSeccion2.setText("Reservar Puesto");

        javax.swing.GroupLayout Seccion2Layout = new javax.swing.GroupLayout(Seccion2);
        Seccion2.setLayout(Seccion2Layout);
        Seccion2Layout.setHorizontalGroup(
            Seccion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Seccion2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelSeccion2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );
        Seccion2Layout.setVerticalGroup(
            Seccion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Seccion2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelSeccion2, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        MenuExpandido.add(Seccion2);

        Seccion3.setBackground(new java.awt.Color(19, 79, 69));
        Seccion3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Seccion3.setMaximumSize(new java.awt.Dimension(220, 30));
        Seccion3.setPreferredSize(new java.awt.Dimension(210, 30));
        Seccion3.setRequestFocusEnabled(false);
        Seccion3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Seccion3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Seccion3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Seccion3MouseExited(evt);
            }
        });

        LabelSeccion3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabelSeccion3.setForeground(new java.awt.Color(255, 255, 255));
        LabelSeccion3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSeccion3.setText("Gestionar Flotas");

        javax.swing.GroupLayout Seccion3Layout = new javax.swing.GroupLayout(Seccion3);
        Seccion3.setLayout(Seccion3Layout);
        Seccion3Layout.setHorizontalGroup(
            Seccion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Seccion3Layout.createSequentialGroup()
                .addComponent(LabelSeccion3, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );
        Seccion3Layout.setVerticalGroup(
            Seccion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Seccion3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelSeccion3)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        MenuExpandido.add(Seccion3);

        Seccion4.setBackground(new java.awt.Color(19, 79, 69));
        Seccion4.setForeground(new java.awt.Color(19, 79, 69));
        Seccion4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Seccion4.setMaximumSize(new java.awt.Dimension(32767, 30));
        Seccion4.setMinimumSize(new java.awt.Dimension(100, 30));
        Seccion4.setPreferredSize(new java.awt.Dimension(210, 30));
        Seccion4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Seccion4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Seccion4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Seccion4MouseExited(evt);
            }
        });

        LabelSeccion4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabelSeccion4.setForeground(new java.awt.Color(255, 255, 255));
        LabelSeccion4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSeccion4.setText("Gestionar Itinerarios");

        javax.swing.GroupLayout Seccion4Layout = new javax.swing.GroupLayout(Seccion4);
        Seccion4.setLayout(Seccion4Layout);
        Seccion4Layout.setHorizontalGroup(
            Seccion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Seccion4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelSeccion4, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );
        Seccion4Layout.setVerticalGroup(
            Seccion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Seccion4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelSeccion4)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        MenuExpandido.add(Seccion4);

        Fondo.add(MenuExpandido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 210, 120));

        Barra.setBackground(new java.awt.Color(255, 255, 255));
        Barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraMouseDragged(evt);
            }
        });
        Barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraMousePressed(evt);
            }
        });
        Barra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonExit.setBackground(new java.awt.Color(255, 255, 255));
        BotonExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonExitMouseExited(evt);
            }
        });

        LabelDeSalida.setBackground(new java.awt.Color(0, 0, 0));
        LabelDeSalida.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LabelDeSalida.setForeground(new java.awt.Color(0, 0, 0));
        LabelDeSalida.setText("X");

        javax.swing.GroupLayout BotonExitLayout = new javax.swing.GroupLayout(BotonExit);
        BotonExit.setLayout(BotonExitLayout);
        BotonExitLayout.setHorizontalGroup(
            BotonExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonExitLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(LabelDeSalida)
                .addGap(28, 28, 28))
        );
        BotonExitLayout.setVerticalGroup(
            BotonExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelDeSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Barra.add(BotonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, 60, 20));

        Fondo.add(Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 20));

        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConductorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConductorActionPerformed

    private void txtFlotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFlotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFlotaActionPerformed

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void txtUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadActionPerformed

    private void txtCapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacidadActionPerformed
    private boolean menuExpandido = false;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        menuExpandido = !menuExpandido;

        // 2. Mostrar u ocultar el panel del menú
        MenuExpandido.setVisible(menuExpandido);

        // 3. Opcional: Asegurarte de que el menú quede por encima de los demás componentes (al frente)
        if (menuExpandido) {
            Fondo.setComponentZOrder(MenuExpandido, 0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Seccion1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Seccion1MouseEntered
        Seccion1.setBackground(new Color(32,135,117));
        LabelSeccion1.setForeground(Color.BLACK);
    }//GEN-LAST:event_Seccion1MouseEntered

    private void Seccion1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Seccion1MouseExited
        Seccion1.setBackground(new Color(19,79,69));
        LabelSeccion1.setForeground(Color.white);
    }//GEN-LAST:event_Seccion1MouseExited

    private void Seccion2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Seccion2MouseEntered
        Seccion2.setBackground(new Color(32,135,117));
        LabelSeccion2.setForeground(Color.BLACK);
    }//GEN-LAST:event_Seccion2MouseEntered

    private void Seccion2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Seccion2MouseExited
        Seccion2.setBackground(new Color(19,79,69));
        LabelSeccion2.setForeground(Color.white);
    }//GEN-LAST:event_Seccion2MouseExited

    private void Seccion3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Seccion3MouseEntered
        Seccion3.setBackground(new Color(32,135,117));
        LabelSeccion3.setForeground(Color.BLACK);
    }//GEN-LAST:event_Seccion3MouseEntered

    private void Seccion3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Seccion3MouseExited
        Seccion3.setBackground(new Color(19,79,69));
        LabelSeccion3.setForeground(Color.white);
    }//GEN-LAST:event_Seccion3MouseExited

    private void Seccion4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Seccion4MouseEntered
        Seccion4.setBackground(new Color(32,135,117));
        LabelSeccion4.setForeground(Color.BLACK);
    }//GEN-LAST:event_Seccion4MouseEntered

    private void Seccion4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Seccion4MouseExited
        Seccion4.setBackground(new Color(19,79,69));
        LabelSeccion4.setForeground(Color.white);
    }//GEN-LAST:event_Seccion4MouseExited

    private void BotonExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_BotonExitMouseClicked

    private void BotonExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonExitMouseEntered
        BotonExit.setBackground(Color.red);
        LabelDeSalida.setForeground(Color.WHITE);
    }//GEN-LAST:event_BotonExitMouseEntered

    private void BotonExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonExitMouseExited
        BotonExit.setBackground(Color.white);
        LabelDeSalida.setForeground(Color.BLACK);
    }//GEN-LAST:event_BotonExitMouseExited

    private void BarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-Xmouse, y-Ymouse);
    }//GEN-LAST:event_BarraMouseDragged

    private void BarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMousePressed
        Xmouse=evt.getX();
        Ymouse=evt.getY();
    }//GEN-LAST:event_BarraMousePressed

    private void Seccion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Seccion1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Seccion1MouseClicked

    private void Seccion3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Seccion3MouseClicked
        InterfazDeFlota1 Verflota= new InterfazDeFlota1();
        Verflota.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Seccion3MouseClicked

    private void Seccion4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Seccion4MouseClicked
        Interfazitinerario1 VerItinerario= new Interfazitinerario1();
        VerItinerario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Seccion4MouseClicked

    private void GuardarUnidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarUnidadMouseClicked
        String campo1= txtConductor.getText();
        String campo2= txtFlota.getText();
        String campo3= txtPlaca.getText();
        String campo4= txtEstado.getText();
        String campo5= txtModelo.getText();
        String campo6= txtUnidad.getText();
        String campo7= txtCapacidad.getText();
        if (interfazFlota1 != null) {
        interfazFlota1.agregarFilaTabla(new Object[]{campo1, campo2, campo3,campo4,campo5,campo6,campo7});
    }
    InterfazDeFlota1 Verflota= new InterfazDeFlota1();
        Verflota.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_GuardarUnidadMouseClicked

    private void txtFlotaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFlotaMousePressed
        txtFlota.setText("");
        txtCapacidad.setText("Ingrese Capacidad");
        txtEstado.setText("Ingrese Estado");
        txtModelo.setText("Ingrese Modelo");
        txtPlaca.setText("Ingrese Placa");
        txtUnidad.setText("Ingrese Unidad");
    }//GEN-LAST:event_txtFlotaMousePressed

    private void txtConductorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConductorMousePressed
        txtConductor.setText("");
        txtFlota.setText("Ingrese Flota");
        txtCapacidad.setText("Ingrese Capacidad");
        txtEstado.setText("Ingrese Estado");
        txtModelo.setText("Ingrese Modelo");
        txtPlaca.setText("Ingrese Placa");
        txtUnidad.setText("Ingrese Unidad");
    }//GEN-LAST:event_txtConductorMousePressed

    private void txtPlacaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPlacaMousePressed
        
        txtCapacidad.setText("Ingrese Capacidad");
        txtEstado.setText("Ingrese Estado");
        txtModelo.setText("Ingrese Modelo");
        txtPlaca.setText("");
        txtUnidad.setText("Ingrese Unidad");
    }//GEN-LAST:event_txtPlacaMousePressed

    private void txtEstadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEstadoMousePressed
        
        txtCapacidad.setText("Ingrese Capacidad");
        txtEstado.setText("");
        txtModelo.setText("Ingrese Modelo");
        txtUnidad.setText("Ingrese Unidad");
    }//GEN-LAST:event_txtEstadoMousePressed

    private void txtModeloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtModeloMousePressed

        txtCapacidad.setText("Ingrese Capacidad");
        txtModelo.setText("");
        txtUnidad.setText("Ingrese Unidad");
    }//GEN-LAST:event_txtModeloMousePressed

    private void txtUnidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUnidadMousePressed

        txtCapacidad.setText("Ingrese Capacidad");
        txtUnidad.setText("");
    }//GEN-LAST:event_txtUnidadMousePressed

    private void txtCapacidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCapacidadMousePressed

        txtCapacidad.setText("");

    }//GEN-LAST:event_txtCapacidadMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazDeFlota2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazDeFlota2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazDeFlota2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazDeFlota2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazDeFlota2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra;
    private javax.swing.JPanel BarraMenu;
    private javax.swing.JPanel BotonExit;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel FotoPerfil;
    private javax.swing.JPanel GuardarUnidad;
    private javax.swing.JLabel LabelDeSalida;
    private javax.swing.JLabel LabelSeccion1;
    private javax.swing.JLabel LabelSeccion2;
    private javax.swing.JLabel LabelSeccion3;
    private javax.swing.JLabel LabelSeccion4;
    private javax.swing.JPanel MenuExpandido;
    private javax.swing.JPanel Seccion1;
    private javax.swing.JPanel Seccion2;
    private javax.swing.JPanel Seccion3;
    private javax.swing.JPanel Seccion4;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtConductor;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFlota;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtUnidad;
    // End of variables declaration//GEN-END:variables
}
