/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modulo_2.Vista;

import java.awt.Color;
import Modulo_1.Vista.Interfaz_Registro;
import Modulo_6.Vista6.InterfazDeFlota1;
/**
 *
 * @author Usuario
 */
public class InterfazLogin extends javax.swing.JFrame {

    int Xmouse, Ymouse;
    public InterfazLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpanelFondo = new javax.swing.JPanel();
        Barra = new javax.swing.JPanel();
        BotonExit = new javax.swing.JPanel();
        LabelDeSalida = new javax.swing.JLabel();
        PanelImagen = new javax.swing.JPanel();
        ImagenDecorativa = new javax.swing.JLabel();
        PanelLogin = new javax.swing.JPanel();
        MensajeLogin = new javax.swing.JLabel();
        Fondoblack1 = new javax.swing.JPanel();
        TextFieldCedula = new javax.swing.JTextField();
        Fondoblack2 = new javax.swing.JPanel();
        TomaDeContraseña = new javax.swing.JPasswordField();
        LogoLogin = new javax.swing.JLabel();
        MensajeLogin1 = new javax.swing.JLabel();
        MensajeLogin2 = new javax.swing.JLabel();
        jPanelRegistro = new javax.swing.JPanel();
        LabelRegistro = new javax.swing.JLabel();
        jPanellogin = new javax.swing.JPanel();
        LabelInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        JpanelFondo.setBackground(new java.awt.Color(255, 255, 255));
        JpanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Barra.setBackground(new java.awt.Color(255, 255, 255));
        Barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraMouseDragged(evt);
            }
        });
        Barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraMousePressed(evt);
            }
        });
        Barra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonExit.setBackground(new java.awt.Color(255, 255, 255));
        BotonExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonExitMouseExited(evt);
            }
        });

        LabelDeSalida.setBackground(new java.awt.Color(0, 0, 0));
        LabelDeSalida.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LabelDeSalida.setForeground(new java.awt.Color(0, 0, 0));
        LabelDeSalida.setText("X");

        javax.swing.GroupLayout BotonExitLayout = new javax.swing.GroupLayout(BotonExit);
        BotonExit.setLayout(BotonExitLayout);
        BotonExitLayout.setHorizontalGroup(
            BotonExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonExitLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(LabelDeSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        BotonExitLayout.setVerticalGroup(
            BotonExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelDeSalida, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        Barra.add(BotonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, 70, 40));

        JpanelFondo.add(Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 40));

        PanelImagen.setBackground(new java.awt.Color(255, 255, 255));
        PanelImagen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenDecorativa.setBackground(new java.awt.Color(0, 0, 0));
        ImagenDecorativa.setForeground(new java.awt.Color(0, 0, 0));
        ImagenDecorativa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modulo_2/Image/Principal.jpg"))); // NOI18N
        ImagenDecorativa.setText("jLabel1");
        PanelImagen.add(ImagenDecorativa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 700));

        JpanelFondo.add(PanelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 700));

        PanelLogin.setBackground(new java.awt.Color(32, 117, 135));

        MensajeLogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        MensajeLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MensajeLogin.setText("Bienvenidos al Sistema de Transporte de la UCV");
        MensajeLogin.setToolTipText("");

        Fondoblack1.setBackground(new java.awt.Color(0, 0, 0));
        Fondoblack1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextFieldCedula.setBackground(new java.awt.Color(255, 255, 255));
        TextFieldCedula.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextFieldCedula.setForeground(new java.awt.Color(51, 51, 51));
        TextFieldCedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldCedula.setText("Ingrese Cedula");
        TextFieldCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextFieldCedulaMousePressed(evt);
            }
        });
        Fondoblack1.add(TextFieldCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 360, 40));

        Fondoblack2.setBackground(new java.awt.Color(0, 0, 0));
        Fondoblack2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TomaDeContraseña.setBackground(new java.awt.Color(255, 255, 255));
        TomaDeContraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TomaDeContraseña.setText("********");
        TomaDeContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TomaDeContraseñaMousePressed(evt);
            }
        });
        Fondoblack2.add(TomaDeContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 360, 40));

        LogoLogin.setBackground(new java.awt.Color(0, 0, 0));
        LogoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modulo_1/Image/Logo.png"))); // NOI18N
        LogoLogin.setText("jLabel2");

        MensajeLogin1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        MensajeLogin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MensajeLogin1.setText("Porfavor ingrese sus datos para ");
        MensajeLogin1.setToolTipText("");

        MensajeLogin2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        MensajeLogin2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MensajeLogin2.setText("acceder al sistema");
        MensajeLogin2.setToolTipText("");

        jPanelRegistro.setBackground(new java.awt.Color(45, 191, 166));
        jPanelRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRegistroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelRegistroMouseExited(evt);
            }
        });

        LabelRegistro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabelRegistro.setForeground(new java.awt.Color(0, 0, 0));
        LabelRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelRegistro.setText("Registrarse");

        javax.swing.GroupLayout jPanelRegistroLayout = new javax.swing.GroupLayout(jPanelRegistro);
        jPanelRegistro.setLayout(jPanelRegistroLayout);
        jPanelRegistroLayout.setHorizontalGroup(
            jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelRegistroLayout.setVerticalGroup(
            jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanellogin.setBackground(new java.awt.Color(234, 197, 48));
        jPanellogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanellogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelloginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelloginMouseExited(evt);
            }
        });

        LabelInicio.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabelInicio.setForeground(new java.awt.Color(0, 0, 0));
        LabelInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelInicio.setText("Iniciar Secion");

        javax.swing.GroupLayout jPanelloginLayout = new javax.swing.GroupLayout(jPanellogin);
        jPanellogin.setLayout(jPanelloginLayout);
        jPanelloginLayout.setHorizontalGroup(
            jPanelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelloginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelloginLayout.setVerticalGroup(
            jPanelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelloginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelLoginLayout = new javax.swing.GroupLayout(PanelLogin);
        PanelLogin.setLayout(PanelLoginLayout);
        PanelLoginLayout.setHorizontalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(MensajeLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(MensajeLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fondoblack1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MensajeLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fondoblack2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanellogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(LogoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        PanelLoginLayout.setVerticalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(LogoLogin)
                .addGap(27, 27, 27)
                .addComponent(MensajeLogin)
                .addGap(18, 18, 18)
                .addComponent(MensajeLogin1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MensajeLogin2)
                .addGap(18, 18, 18)
                .addComponent(Fondoblack1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Fondoblack2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanellogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        JpanelFondo.add(PanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 500, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1196, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMousePressed
        Xmouse=evt.getX();
        Ymouse=evt.getY();
    }//GEN-LAST:event_BarraMousePressed

    private void BarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-Xmouse, y-Ymouse);
    }//GEN-LAST:event_BarraMouseDragged

    private void BotonExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_BotonExitMouseClicked

    private void BotonExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonExitMouseEntered
       BotonExit.setBackground(Color.red);
       LabelDeSalida.setForeground(Color.WHITE);
    }//GEN-LAST:event_BotonExitMouseEntered

    private void BotonExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonExitMouseExited
       BotonExit.setBackground(Color.white);
       LabelDeSalida.setForeground(Color.BLACK);
    }//GEN-LAST:event_BotonExitMouseExited

    private void jPanelRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRegistroMouseEntered
        jPanelRegistro.setBackground(new Color(57,242,210));
        LabelRegistro.setForeground(Color.white);
    }//GEN-LAST:event_jPanelRegistroMouseEntered

    private void jPanelRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRegistroMouseExited
       jPanelRegistro.setBackground(new Color(45,191,166));
        LabelRegistro.setForeground(Color.black);
    }//GEN-LAST:event_jPanelRegistroMouseExited

    private void jPanelloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelloginMouseEntered
        jPanellogin.setBackground(new Color(241,190,65));
        LabelInicio.setForeground(Color.white);
    }//GEN-LAST:event_jPanelloginMouseEntered

    private void jPanelloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelloginMouseExited
       jPanellogin.setBackground(new Color(234,197,48));
        LabelInicio.setForeground(Color.black);
    }//GEN-LAST:event_jPanelloginMouseExited

    private void TextFieldCedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldCedulaMousePressed
        if(TextFieldCedula.getText().equals("Ingrese Cedula")){
        TextFieldCedula.setText("");
        }
        if(String.valueOf(TomaDeContraseña.getPassword()).isEmpty()){
        TomaDeContraseña.setText("********");
        }
    }//GEN-LAST:event_TextFieldCedulaMousePressed

    private void TomaDeContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TomaDeContraseñaMousePressed
        if(String.valueOf(TomaDeContraseña.getPassword()).equals("********")){
        TomaDeContraseña.setText("");
        }
        if(TextFieldCedula.getText().isEmpty()){
        TextFieldCedula.setText("Ingrese Cedula");
        }  
    }//GEN-LAST:event_TomaDeContraseñaMousePressed

    private void jPanelRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRegistroMouseClicked
        Interfaz_Registro irRegistro= new Interfaz_Registro();
        irRegistro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelRegistroMouseClicked

    private void jPanelloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelloginMouseClicked
        InterfazDeFlota1 IraFlotas = new InterfazDeFlota1();
        IraFlotas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelloginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra;
    private javax.swing.JPanel BotonExit;
    private javax.swing.JPanel Fondoblack1;
    private javax.swing.JPanel Fondoblack2;
    private javax.swing.JLabel ImagenDecorativa;
    private javax.swing.JPanel JpanelFondo;
    private javax.swing.JLabel LabelDeSalida;
    private javax.swing.JLabel LabelInicio;
    private javax.swing.JLabel LabelRegistro;
    private javax.swing.JLabel LogoLogin;
    private javax.swing.JLabel MensajeLogin;
    private javax.swing.JLabel MensajeLogin1;
    private javax.swing.JLabel MensajeLogin2;
    private javax.swing.JPanel PanelImagen;
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JTextField TextFieldCedula;
    private javax.swing.JPasswordField TomaDeContraseña;
    private javax.swing.JPanel jPanelRegistro;
    private javax.swing.JPanel jPanellogin;
    // End of variables declaration//GEN-END:variables
}
